apiVersion: v1
kind: Namespace
metadata:
  name: pi-hole
---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole-service
  namespace: pi-hole
  annotations:
    metallb.io/loadBalancerIPs: "10.214.0.88"
spec:
  type: LoadBalancer
  ports:
    - port: 53
      name: dns-udp
      protocol: UDP
    - port: 53
      name: dns-tcp
      protocol: TCP
    - port: 80
      name: http
      protocol: TCP
  selector:
    app: pi-hole
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pi-hole
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - cluster
      containers:
        - name: pi-hole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: America/Toronto
            - name: FTLCONF_dns_listeningMode
              value: all
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 80
              name: http
          volumeMounts:
            - name: pi-hole-storage
              mountPath: /etc/pihole
  volumeClaimTemplates:
    - metadata:
        name: pi-hole-storage
        namespace: pi-hole
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: cluster-storage
        resources:
          requests:
            storage: 5Gi

## Suggested by Reddit
## https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt
##
