apiVersion: v1
kind: Service
metadata:
  name: load-balancer-longhorn-ui
  namespace: longhorn-system
  # annotations:
  #   metallb.io/loadBalancerIPs: 10.214.0.20
    # kube-vip.io/loadbalancerIPs: 10.214.0.20
spec:
  type: LoadBalancer
  selector:
    app: longhorn-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
