apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cluster-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  fsType: "ext4"
  nodeSelector: "cluster"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ai-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  fsType: "ext4"
  nodeSelector: "ai"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devel-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  fsType: "ext4"
  nodeSelector: "devel"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: external-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  fsType: "ext4"
  nodeSelector: "external"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devel-storage
provisioner: nfs.csi.k8s.io
mountOptions:
  - vers=4.1
parameters:
  server: 192.168.7.227
  share: /volume1/devel      # Replace with your NFS share path
reclaimPolicy: Retain        # Keeps data if PVC is deleted
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database-storage
provisioner: iscsi.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
