apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: database-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  fsType: "ext4"
  nodeSelector: "database"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ai-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  fsType: "ext4"
  nodeSelector: "ai"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devel-strict-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  fsType: "ext4"
  nodeSelector: "devel"
