---
- name: Initialize K3S primary control plane
  hosts: kube_prime_node
  become: true
  vars_files:
    - ../k3s-vars.yaml
  tasks:
    - name: Init cluster on primary node
      ansible.builtin.shell: |
        echo curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server --disable=servicelb --cluster-init

   # kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/main/config/manifests/metallb-native.yaml
   # kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.12.0/deploy/longhorn.yaml
   # kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

   # curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/v4.13.4/deploy/install-driver.sh | bash -s v4.13.4 --
   # ## not installed yet # curl -skSL https://raw.githubusercontent.com/kubernetes-csi/csi-driver-iscsi/master/deploy/install-driver.sh | bash -s master --
   #
---
- name: Initialize K3S seconday control planes
  hosts: kube_secondary_nodes
  become: true
  vars_files:
    - ../k3s-vars.yaml
  tasks:
    - name: Init cluster on seconday nodes
      ansible.builtin.shell: |
        echo curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server --disable=servicelb --server https://{{ k3s_prime_ip }}:6443

---
- name: Initialize K3S control planes
  hosts: kube_control_plane_nodes
  become: true
  tasks:
    - name: Make kube directory
      ansible.builtin.file:
        path: /home/ansible/.kube
        state: directory
        mode: '0755'
        owner: ansible
        group: ansible

    - name: Copy kube config file
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ansible/.kube/config
        mode: '600'
        owner: ansible
        group: ansible
        remote_src: true

    - name: Append KUBECONFIG to end of .profile
      ansible.builtin.lineinfile:
        path: /home/ansible/.profile
        line: export KUBECONFIG="/home/ansible/.kube/config"
