router bgp 65000
  bgp router-id 192.168.1.1
  no bgp ebgp-requires-policy
  neighbor 192.168.7.63 remote-as 65001
  neighbor 192.168.7.63 soft-reconfiguration inbound
  neighbor 192.168.7.193 remote-as 65001
  neighbor 192.168.7.193 soft-reconfiguration inbound
  neighbor 192.168.7.82 remote-as 65001
  neighbor 192.168.7.82 soft-reconfiguration inbound

address-family ipv4 unicast
  network 10.214.0.0/24
  neighbor 192.168.7.63 activate
  neighbor 192.168.7.193 activate
  neighbor 192.168.7.82 activate
exit-address-family
